# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
    target-branch: main
    groups:
      development-dependencies:
        dependency-type: development
        exclude-patterns:
          - erb_lint*
          - standard
      erb_lint:
        patterns:
          - erb_lint*
      standard:
        patterns:
          - standard
