version: '3.1'

services:
  postgres:
    container_name: tdt-postgres
    restart: always
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: tdtalent
    volumes:
      - tdt-pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    container_name: tdt-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - tdt-redis:/data
  app:
    user: vscode
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    links:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:tdtalent@postgres/
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
volumes:
  tdt-redis:
    driver: local
  tdt-pg:
    driver: local