shared:
  support: jobs@tampadevs.com
  support_mailbox: "Tampa Devs Talent <jobs@tampadevs.com>"
  notifications_mailbox: "Tampa Devs Talent <jobs@tampadevs.com>"
  updates_mailbox: "Tampa Devs Talent <jobs@tampadevs.com>"
  reminders_mailbox: "Tampa Devs Talent <jobs@tampadevs.com>"
