shared:
  -
    image: nicole.jpg
    name: Nicole Rinaldo
    testimonial: We are thrilled with our experience using Tampa Devs Talent. We hired two qualified developers through the platform in our first month and it will now be our go-to for finding skilled, reliable, vetted talent. Highly recommend!
    title: Chief People Officer, Peaceful Media
    url: https://peacefulmedia.com/
#  -
#    image: phil.jpg
#    name: Phil
#    testimonial: My lead developer gave notice and I found a replacement in under a week through RailsDevs.
#    title: Founder, Theatre Digs Booker
#    url: https://testimonial.to/share/railsdevs-hiring/t/5nDZ3xmVezbr8NvNzy2qpdWj9
